# Generated by Django 6.0.3 on 2026-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='handled_by',
            field=models.CharField(choices=[('ai', '🤖 Inteligência Artificial'), ('human', '👤 Atendente Humano')], default='ai', max_length=20, verbose_name='Atendido por'),
        ),
    ]
