# Generated by Django 6.0.3 on 2026-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='chatwoot_contact_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chatwoot Contact ID'),
        ),
        migrations.AddField(
            model_name='lead',
            name='chatwoot_conversation_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chatwoot Conversation ID'),
        ),
    ]
