# Generated by Django 6.0.3 on 2026-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_chatwoot_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='handled_by',
            field=models.CharField(choices=[('ai', '🤖 Inteligência Artificial'), ('human', '👤 Atendente Humano')], default='human', max_length=20, verbose_name='Atendido por'),
        ),
    ]
