# Generated by Django 6.0.3 on 2026-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_potential',
            field=models.BooleanField(default=False, verbose_name='Lead Potencial'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('in', 'Recebida (Paciente)'), ('out', 'Enviada (Antigo)'), ('out_human', 'Enviada (Secretária)'), ('out_ai', 'Enviada (IA)')], max_length=10, verbose_name='Direção'),
        ),
    ]
